const actionsTypes = {
    FETCH_BOOKS_REQUEST: 'FETCH_BOOKS_REQUEST',
    FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
    FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE',
    BOOK_ADD_TO_CART: 'BOOK_ADD_TO_CART',
    BOOK_DELETE_FROM_CART: 'BOOK_DELETE_FROM_CART',
    ALL_BOOK_DELETE_FROM_CART: 'ALL_BOOK_DELETE_FROM_CART'
}

export default actionsTypes